### ISSUE TITLE
[Kidgoddess] Error on tracking

### ISSUE THREAD

**Issue by thongphp** [jooservices/XGallery#91]
- [ ] Client error: GET https://kissgoddess.com/gallery//31.html resulted in a 404 Not Found response
- [ ] Client error: GET https://kissgoddess.com/album/32313_10_1.html resulted in a 404 Not Found response
- [x] Can not get download URL: https://pic.kissgoddess.com/gallery/27652/32313/s/0.jpg
- [x] Can not get download URL: https://pic.kissgoddess.com/gallery/27652/32313/s/0.jpg. Error: SSL certificate problem: certificate has expired
